### ISSUE TITLE
Opening book

### ISSUE THREAD

**Issue by tissatussa** [bdmendes/camel#13]
hi, i just discovered your engine by the Public download list at https://drive.google.com/drive/folders/1vmtiWtIZoBDqkarEm1_rLT9_l0eq0qr3 .. i managed to compile v0.3.1 on Xubuntu 22.04 and it runs fine in CuteChess (GUI) !

however, Camel does not seem to know how to play the opening : it likes to develop the Queens kNight to c3 / c6 very early in the opening, it often just starts with that move, and this is a difficult setup : it's playable, but the move blocks the c-pawn and the kNight can easily be kicked to other squares, none of which are safe .. the kNight might be captured .. if not, Camel will get a bad position where all pieces are disharmonious ..

this might sound harsh, but i'm a chess player myself .. and i gather and test many chess engines (only on Linux) also weaker ones, and i know many such engines have the same habbit : their pawn-piece setup is bad, the Queens kNight should not be developed that way .. normally .. it CAN be played (SF knows how), it's a known opening, but rare and you must know how to put the (other) pieces ..

here's a game of Camel playing Black :

![LiChess-game-animation-oflxr8m7](https://user-images.githubusercontent.com/1109281/236676462-7ec91cb4-80a4-416c-a5b8-c31bef622800.gif)

i'm a programmer, but not yet of any engine .. i don't know how you can improve Camel with my information .. but maybe when NOT playing Nc3 / Nc6 early, Camel can play a decent game ?

**Comment by bdmendes** [comment]
Hi! Thank you for passing by. Currently, Camel uses a very simple evaluation technique, based on material, piece squares and some basic pawn structure considerations. This means that it struggles to play openings since it has no notion of space and development yet.
Actually, even if it had, engines usually have some trouble playing openings and thus they resort to an opening book. Since I'm running the bot on Lichess, which has the option to provide its own opening book, I'm not worrying too much about that at this moment. But it is definitely a future improvement; feel free to fork and experiment.
